

services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - 0.0.0.0:9092
      - --advertise-kafka-addr
      - redpanda:9092
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agri
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  spark:
    image: apache/spark:3.5.0
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"

  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    environment:
        JUPYTER_TOKEN: password


#for automation
  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    depends_on:
      - redpanda
    entrypoint: >
      /bin/sh -c "
        until rpk cluster info --brokers redpanda:9092 > /dev/null 2>&1; do
          echo 'Attente Redpanda...' && sleep 5;
        done &&
        rpk topic create capteurs_agri --brokers redpanda:9092 || true &&
        rpk topic create meteo_externe --brokers redpanda:9092 || true &&
        rpk topic create alertes_agri --brokers redpanda:9092 || true &&
        echo 'Topics créés ✅'
      "

  producer:
    image: python:3.10-slim
    depends_on:
      - redpanda-init
    volumes:
      - .:/app
    working_dir: /app
    environment:
      KAFKA_BROKER: redpanda:9092
    command: >
      /bin/sh -c "
        pip install kafka-python -q &&
        python producers/capteurs_sol.py
      "

  transformation:
    image: apache/spark:3.5.0
    depends_on:
      - producer
    user: root
    volumes:
      - .:/app
    working_dir: /app
    environment:
      KAFKA_BROKER: redpanda:9092
    entrypoint: /bin/bash
    command:
      - -c
      - |
        pip install kafka-python --quiet
        /opt/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0 /app/spark/transformation.py
  storage:
    image: python:3.10-slim
    depends_on:
      - redpanda-init
      - postgres
      - minio
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/sh -c "
        pip install kafka-python pandas minio psycopg2-binary pyarrow -q &&
        python storage/minio_upload.py &
        python storage/postgres_insert.py
      "
  interface:
    image: python:3.10-slim
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/sh -c "
        pip install streamlit psycopg2-binary pandas altair -q &&
        streamlit run 'interface/dashboard.py' --server.port 8501 --server.address 0.0.0.0
      "
    ports:
      - "8501:8501"
