version: '3.8'

services:

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
    ports:
      - "9092:9092"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agri
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  spark:
    image: apache/spark:3.5.0
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"

  jupyter:
    image: jupyter/base-notebook
    ports:
      - "8888:8888"
    environment:
        JUPYTER_TOKEN: password


#for automation
  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.1
    depends_on:
      - redpanda
    entrypoint: >
      /bin/sh -c "
        sleep 30 &&
        rpk topic create capteurs_agri --brokers redpanda:9092 &&
        rpk topic create meteo_externe --brokers redpanda:9092 &&
        rpk topic create alertes_agri --brokers redpanda:9092 &&
        echo 'Topics créés.'
      "

  producer:
    build: .
    depends_on:
      - redpanda-init
    command: python producers/capteurs_iot_producer.py

  transformation:
    build: .
    depends_on:
      - producer
    command: python spark/transformation.py

  storage:
    build: .
    depends_on:
      - transformation
      - postgres
      - minio
    command: >
      /bin/sh -c "
      sleep 15 &&
      python storage/minio_upload.py &&
      python storage/postgres_insert.py
      "
